name: Ada (GNAT)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du code source
    - name: Checkout
      uses: actions/checkout@v4

    # Étape 2 : Installation de GNAT et outils de build
    - name: Set up GNAT toolchain
      run: |
        sudo apt-get update &&
        sudo apt-get install -y gnat gprbuild

    # Étape 3 : Compilation du projet
    - name: Build
      run: gprbuild -P src/pim.gpr -j0 -p

    - name: Debug Build Directory
      run: ls -R ${{ github.workspace }}/build
      
    # Étape 4 : Exécution des tests
    - name: Run Tests
      run: |
        if [ -f "build/bin/testfamilytree" ]; then
          chmod +x "build/bin/testfamilytree"
          "build/bin/testfamilytree"
        else
          echo "Test binary not found!"
          exit 1
        fi
